<a href="https://colab.research.google.com/github/lucid005/AI-and-Machine-Learning/blob/main/Worksheet0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

####Name: Saurav Shrestha
####Group: L6CG9
####ID: 2408619

#4 TO-DO-Task
Please complete all the problem listed below.
4.1 Exercise on Functions:
##Task- 1:
Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.
• Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.
• Conversion Options:
1. Length:– Convert meters (m) to feet (ft).– Convert feet (ft) to meters (m).
2. Weight:– Convert kilograms (kg) to pounds (lbs).– Convert pounds (lbs) to kilograms (kg).
3. Volume:– Convert liters (L) to gallons (gal).– Convert gallons (gal) to liters (L)

In [11]:
def unit_converter():
    """
    Converts between different measurement units.

    The function asks the user to choose a conversion type
    (length, weight, or volume) and then performs the selected
    conversion based on the value entered by the user.

    Returns:
        None
    """

    try:
        print("Choose conversion type:")
        print("1. Length")
        print("2. Weight")
        print("3. Volume")

        choice = input("Enter your choice (1/2/3): ")

        value = float(input("Enter the value to convert: "))

        if choice == "1":
            print("Length conversion:")
            print("1. Meters to Feet")
            print("2. Feet to Meters")

            option = input("Choose option (1/2): ")

            if option == "1":
                result = value * 3.28084
                print(value, "meters =", result, "feet")

            elif option == "2":
                result = value / 3.28084
                print(value, "feet =", result, "meters")

            else:
                print("Invalid length conversion option")

        elif choice == "2":
            print("Weight conversion:")
            print("1. Kilograms to Pounds")
            print("2. Pounds to Kilograms")

            option = input("Choose option (1/2): ")

            if option == "1":
                result = value * 2.20462
                print(value, "kg =", result, "lbs")

            elif option == "2":
                result = value / 2.20462
                print(value, "lbs =", result, "kg")

            else:
                print("Invalid weight conversion option")

        elif choice == "3":
            print("Volume conversion:")
            print("1. Liters to Gallons")
            print("2. Gallons to Liters")

            option = input("Choose option (1/2): ")

            if option == "1":
                result = value * 0.264172
                print(value, "liters =", result, "gallons")

            elif option == "2":
                result = value / 0.264172
                print(value, "gallons =", result, "liters")

            else:
                print("Invalid volume conversion option")

        else:
            print("Invalid conversion type")

    except ValueError:
        print("Error: Please enter a valid numeric value.")


# Run the program
unit_converter()

Choose conversion type:
1. Length
2. Weight
3. Volume
Enter your choice (1/2/3): 1
Enter the value to convert: 20
Length conversion:
1. Meters to Feet
2. Feet to Meters
Choose option (1/2): 1
20.0 meters = 65.6168 feet


##Task- 2:
Create a Python program that performs various mathematical operations on a list of numbers.
• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).
3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.

• Requirements:
1. Functions: Define at least one function for each operation (sum, average, maximum, mini
mum).
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.

In [13]:
def calculate_sum(numbers):
    """
    Calculates the sum of a list of numbers.

    Parameters:
        numbers (list): A list of numeric values.

    Returns:
        float: The sum of the numbers.
    """
    return sum(numbers)


def calculate_average(numbers):
    """
    Calculates the average of a list of numbers.

    Parameters:
        numbers (list): A list of numeric values.

    Returns:
        float: The average value.
    """
    return sum(numbers) / len(numbers)


def find_max(numbers):
    """
    Finds the maximum value in a list of numbers.

    Parameters:
        numbers (list): A list of numeric values.

    Returns:
        float: The largest number.
    """
    return max(numbers)


def find_min(numbers):
    """
    Finds the minimum value in a list of numbers.

    Parameters:
        numbers (list): A list of numeric values.

    Returns:
        float: The smallest number.
    """
    return min(numbers)


try:
    print("Choose an operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    choice = input("Enter your choice (1/2/3/4): ")

    user_input = input("Enter numbers separated by spaces: ")
    numbers = [float(x) for x in user_input.split()]

    if len(numbers) == 0:
        raise ValueError("List cannot be empty")

    if choice == "1":
        result = calculate_sum(numbers)
        print("Sum =", result)

    elif choice == "2":
        result = calculate_average(numbers)
        print("Average =", result)

    elif choice == "3":
        result = find_max(numbers)
        print("Maximum =", result)

    elif choice == "4":
        result = find_min(numbers)
        print("Minimum =", result)

    else:
        print("Invalid operation selected.")

except ValueError:
    print("Error: Please enter valid numbers separated by spaces.")

Choose an operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter your choice (1/2/3/4): 1
Enter numbers separated by spaces: 20 20
Sum = 40.0


#4.2 Exercise on List Manipulation:
##1. Extract Every Other Element:
Write a Python function that extracts every other element from a list, starting from the first element.
• Requirements:– Define a function extract
every
other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [1]:
def extract_every_other(lst):
    """
    Returns every other element from a list starting from the first element.

    Parameters:
        lst (list): The input list.

    Returns:
        list: A new list containing every other element.
    """
    return lst[::2]


# Example
numbers = [1, 2, 3, 4, 5, 6]
result = extract_every_other(numbers)
print(result)

[1, 3, 5]


##2. Slice a Sublist:
Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.
• Requirements:– Define a function get
sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5]

In [2]:
def get_sublist(lst, start, end):
    """
    Returns a sublist from the given list from index start to end (inclusive).

    Parameters:
        lst (list): The input list.
        start (int): Starting index.
        end (int): Ending index.

    Returns:
        list: The extracted sublist.
    """
    return lst[start:end+1]


# Example
numbers = [1, 2, 3, 4, 5, 6]
result = get_sublist(numbers, 2, 4)
print(result)

[3, 4, 5]


##3. Reverse a List Using Slicing:
Write a Python function that reverses a list using slicing.
• Requirements:– Define a function reverse
slicing.
list(lst) that takes a list lst and returns a reversed list using– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1]

In [3]:
def reverse_list(lst):
    """
    Reverses a list using slicing.

    Parameters:
        lst (list): The input list.

    Returns:
        list: A reversed version of the list.
    """
    return lst[::-1]


# Example
numbers = [1, 2, 3, 4, 5]
result = reverse_list(numbers)
print(result)

[5, 4, 3, 2, 1]


##4. Remove the First and Last Elements:
Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.
• Requirements:– Defineafunction remove
first
last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [4]:
def remove_first_last(lst):
    """
    Removes the first and last elements from a list.

    Parameters:
        lst (list): The input list.

    Returns:
        list: A new list without the first and last elements.
    """
    return lst[1:-1]


# Example
numbers = [1, 2, 3, 4, 5]
result = remove_first_last(numbers)
print(result)

[2, 3, 4]


##5. Get the First n Elements:
Write a Python function that extracts the first n elements from a list.
• Requirements:– Define a function get
first
n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [5]:
def get_first_n(lst, n):
    """
    Returns the first n elements from a list.

    Parameters:
        lst (list): The input list.
        n (int): Number of elements to extract.

    Returns:
        list: A list containing the first n elements.
    """
    return lst[:n]


# Example
numbers = [1, 2, 3, 4, 5]
result = get_first_n(numbers, 3)
print(result)

[1, 2, 3]


##6. Extract Elements from the End:
Write a Python function that extracts the last n elements of a list using slicing.
• Requirements:– Define a function get
last
n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [6]:
def get_last_n(lst, n):
    """
    Returns the last n elements from a list.

    Parameters:
        lst (list): The input list.
        n (int): Number of elements to extract from the end.

    Returns:
        list: A list containing the last n elements.
    """
    return lst[-n:]


# Example
numbers = [1, 2, 3, 4, 5]
result = get_last_n(numbers, 2)
print(result)

[4, 5]


##7. Extract Elements in Reverse Order:
Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.
• Requirements:– Define a function reverse
skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [7]:
def reverse_skip(lst):
    """
    Returns elements in reverse order starting from the
    second-to-last element and skipping one element each time.

    Parameters:
        lst (list): The input list.

    Returns:
        list: A list containing every second element in reverse order.
    """
    return lst[-2::-2]


# Example
numbers = [1, 2, 3, 4, 5, 6]
result = reverse_skip(numbers)
print(result)

[5, 3, 1]


#4.3 Exercise on Nested List:
##1. Flatten a Nested List:
Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.
• Requirements:– Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [8]:
def flatten(lst):
    """
    Flattens a nested list into a single list.

    Parameters:
        lst (list): A nested list containing sublists.

    Returns:
        list: A flattened list containing all elements.
    """
    flat_list = []

    for sublist in lst:
        for item in sublist:
            flat_list.append(item)

    return flat_list


# Example
numbers = [[1, 2], [3, 4], [5]]
result = flatten(numbers)
print(result)

[1, 2, 3, 4, 5]


##2. Accessing Nested List Elements:
Write a Python function that extracts a specific element from a nested list given its indices.
• Requirements:– Define a function access
nested
element(lst, indices) that takes a nested list lst and
a list of indices indices, and returns the element at that position.– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
2], the output should be 6

In [9]:
def access_nested_element(lst, indices):
    """
    Accesses a specific element from a nested list using given indices.

    Parameters:
        lst (list): The nested list.
        indices (list): A list of indices indicating the position.

    Returns:
        element: The element at the specified position.
    """
    element = lst

    for i in indices:
        element = element[i]

    return element


# Example
lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]

result = access_nested_element(lst, indices)
print(result)

6


##3. Sum of All Elements in a Nested List:
Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).
• Requirements:– Define a function sum
nested(lst) that takes a nested list lst and returns the sum of all
the elements.– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [10]:
def sum_nested(lst):
    """
    Calculates the sum of all numbers in a nested list.

    Parameters:
        lst (list): A nested list containing numbers.

    Returns:
        int/float: The sum of all numbers in the nested list.
    """
    total = 0

    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item

    return total


# Example
numbers = [[1, 2], [3, [4, 5]], 6]
result = sum_nested(numbers)
print(result)

21


##4. Remove Specific Element from a Nested List:
Write a Python function that removes all occurrences of a specific element from a nested list.
• Requirements:– Define a function remove
element(lst, elem) that removes elem from lst and returns the
modified list.– Example: Fortheinput lst = [[1, 2], [3, 2], [4, 5]]andelem = 2,theoutputshould
be [[1], [3], [4, 5]].

In [ ]:
def remove_element(lst, elem):
    """
    Removes all occurrences of a specific element from a nested list.

    Parameters:
        lst (list): A nested list.
        elem: The element to remove.

    Returns:
        list: The modified nested list with the element removed.
    """
    result = []

    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        else:
            if item != elem:
                result.append(item)

    return result


# Example
lst = [[1, 2], [3, 2], [4, 5]]
elem = 2

print(remove_element(lst, elem))

[[1], [3], [4, 5]]


##5. Find the Maximum Element in a Nested List:
Write a Python function that finds the maximum element in a nested list (regardless of depth).
• Requirements:– Define a function find
element.
max(lst) that takes a nested list lst and returns the maximum– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6

In [ ]:
def find_max(lst):
    """
    Finds the maximum value in a nested list.

    Parameters:
        lst (list): A nested list containing numbers.

    Returns:
        int/float: The maximum value found in the list.
    """
    maximum = None

    for item in lst:
        if isinstance(item, list):
            value = find_max(item)
        else:
            value = item

        if maximum is None or value > maximum:
            maximum = value

    return maximum


# Example
numbers = [[1, 2], [3, [4, 5]], 6]
result = find_max(numbers)
print(result)

6


##6. Count Occurrences of an Element in a Nested List:
Write a Python function that counts how many times a specific element appears in a nested list.
• Requirements:– Define a function count
occurrences(lst, elem) that counts the occurrences of elem in
the nested list lst.– Example: Fortheinput lst = [[1, 2], [2, 3], [2, 4]]andelem = 2,theoutputshould
be 3.

In [ ]:
def count_occurrences(lst, elem):
    """
    Counts how many times an element appears in a nested list.

    Parameters:
        lst (list): A nested list.
        elem: The element to count.

    Returns:
        int: The number of times the element appears.
    """
    count = 0

    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        else:
            if item == elem:
                count += 1

    return count


# Example
lst = [[1, 2], [2, 3], [2, 4]]
elem = 2

print(count_occurrences(lst, elem))

3


##7. Flatten a List of Lists of Lists:
Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.
• Requirements:– Define a function deep
flatten(lst) that takes a deeply nested list lst and returns a single
f
lattened list.– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
[1, 2, 3, 4, 5, 6, 7, 8].

In [ ]:
def deep_flatten(lst):
    """
    Flattens a deeply nested list into a single list.

    Parameters:
        lst (list): A list that may contain other nested lists.

    Returns:
        list: A flattened list containing all elements.
    """
    result = []

    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)

    return result


# Example
numbers = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
result = deep_flatten(numbers)
print(result)

[1, 2, 3, 4, 5, 6, 7, 8]


##8. Nested List Average:
Write a Python function that calculates the average of all elements in a nested list.
• Requirements:– Define a function average
of all the elements.
nested(lst) that takes a nested list lst and returns the average– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [ ]:
def average_nested(lst):
    """
    Calculates the average of all elements in a nested list.

    Parameters:
        lst (list): A nested list containing numbers.

    Returns:
        float: The average of all numbers in the nested list.
    """

    flat_list = []

    def flatten(x):
        for item in x:
            if isinstance(item, list):
                flatten(item)
            else:
                flat_list.append(item)

    flatten(lst)

    return sum(flat_list) / len(flat_list)


# Example
numbers = [[1, 2], [3, 4], [5, 6]]
result = average_nested(numbers)
print(result)

3.5


#10 To- Do- NumPy
Please complete all the problems listed below:
10.1 Basic Vector and Matrix Operation with Numpy.
##Problem- 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np

# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("Empty array (2x2):")
print(empty_array)

# 2. Initialize an all-one array with size 4x2
ones_array = np.ones((4, 2))
print("\nAll ones array (4x2):")
print(ones_array)

# 3. Create a new array filled with a specific value
filled_array = np.full((3, 3), 7)   # example: shape (3x3) filled with 7
print("\nArray filled with value 7:")
print(filled_array)

# 4. Create a zeros array with same shape and type as a given array
zeros_like_array = np.zeros_like(ones_array)
print("\nZeros array like ones_array:")
print(zeros_like_array)

# 5. Create a ones array with same shape and type as a given array
ones_like_array = np.ones_like(empty_array)
print("\nOnes array like empty_array:")
print(ones_like_array)

# 6. Convert list to NumPy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nNumPy array converted from list:")
print(numpy_array)

Empty array (2x2):
[[1.70194460e-315 0.00000000e+000]
 [6.66179363e-310 6.66179363e-310]]

All ones array (4x2):
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Array filled with value 7:
[[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros array like ones_array:
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

Ones array like empty_array:
[[1. 1.]
 [1. 1.]]

NumPy array converted from list:
[1 2 3 4]


##Problem- 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np

# 1. Array values from 10 to 49
arr1 = np.arange(10, 50)
print("1) 10 to 49:\n", arr1)

# 2. 3x3 matrix values from 0 to 8
arr2 = np.arange(0, 9).reshape(3, 3)
print("\n2) 3x3 matrix 0 to 8:\n", arr2)

# 3. 3x3 identity matrix
arr3 = np.eye(3)
print("\n3) Identity matrix 3x3:\n", arr3)

# 4. Random array of size 30 and mean
arr4 = np.random.random(30)
mean_val = arr4.mean()
print("\n4) Random size 30:\n", arr4)
print("Mean:", mean_val)

# 5. 10x10 random array and min/max
arr5 = np.random.random((10, 10))
min_val = arr5.min()
max_val = arr5.max()
print("\n5) 10x10 random:\n", arr5)
print("Min:", min_val)
print("Max:", max_val)

# 6. Zero array size 10 and replace 5th element with 1
arr6 = np.zeros(10)
arr6[4] = 1   # 5th element is index 4
print("\n6) Zero array with 5th element = 1:\n", arr6)

# 7. Reverse an array arr = [1,2,0,0,4,0]
arr7 = np.array([1, 2, 0, 0, 4, 0])
reversed_arr7 = arr7[::-1]
print("\n7) Reversed array:\n", reversed_arr7)

# 8. 2D array with 1 on border and 0 inside
arr8 = np.ones((5, 5))
arr8[1:-1, 1:-1] = 0
print("\n8) Border 1, inside 0:\n", arr8)

# 9. 8x8 checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[::2, 1::2] = 1
checkerboard[1::2, ::2] = 1
print("\n9) 8x8 checkerboard:\n", checkerboard)

1) 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2) 3x3 matrix 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3) Identity matrix 3x3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4) Random size 30:
 [0.82700102 0.42843544 0.9456295  0.38092272 0.5757291  0.79093555
 0.92007166 0.30046967 0.42041382 0.85249212 0.27102661 0.95545553
 0.02065989 0.39358657 0.21007061 0.15987091 0.84119688 0.88987694
 0.30663831 0.30047263 0.74914896 0.16544961 0.21920908 0.99737414
 0.90342858 0.47069358 0.25614507 0.9090864  0.49285232 0.7149582 ]
Mean: 0.5556433801222398

5) 10x10 random:
 [[0.6795641  0.19793238 0.28175984 0.01406917 0.53017999 0.82941203
  0.51912248 0.09419736 0.28416867 0.16040369]
 [0.61032789 0.63055349 0.1002059  0.72805137 0.5056905  0.25393993
  0.65478249 0.65383354 0.32680373 0.26774006]
 [0.04936276 0.38147687 0.19699174 0.33733817 0.40399368 0.14648338
  0.97222453 0.0119205  0.62843485 0.62365594]
 [

##Problem- 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
import numpy as np

# Given arrays
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

# 1. Add the two arrays
add_xy = x + y
print("1) Addition:\n", add_xy)

# 2. Subtract the two arrays
sub_xy = x - y
print("\n2) Subtraction:\n", sub_xy)

# 3. Multiply the array with an integer
mul_x = x * 2
print("\n3) Multiply x by 2:\n", mul_x)

# 4. Square of each element
square_x = x ** 2
print("\n4) Square of elements in x:\n", square_x)

# 5. Dot products
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)

print("\n5) Dot products:")
print("v · w =", dot_vw)
print("x · v =", dot_xv)
print("x · y =\n", dot_xy)

# 6. Concatenate arrays
concat_xy_row = np.vstack((x, y))
concat_vw_col = np.vstack((v, w)).T

print("\n6) Concatenate x and y along rows:\n", concat_xy_row)
print("\nConcatenate v and w along columns:\n", concat_vw_col)

# 7. Try concatenating x and v
try:
    concat_xv = np.concatenate((x, v))
    print("\n7) Concatenate x and v:\n", concat_xv)
except ValueError as e:
    print("\n7) Error when concatenating x and v:", e)

1) Addition:
 [[ 6  8]
 [10 13]]

2) Subtraction:
 [[-4 -4]
 [-4 -3]]

3) Multiply x by 2:
 [[ 2  4]
 [ 6 10]]

4) Square of elements in x:
 [[ 1  4]
 [ 9 25]]

5) Dot products:
v · w = 219
x · v = [29 77]
x · y =
 [[19 22]
 [50 58]]

6) Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v and w along columns:
 [[ 9 11]
 [10 12]]

7) Error when concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


##Problem- 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB̸ = BA.
3. Prove (AB)T = BTAT.
• Solve the following system of Linear equation using Inverse Methods.
2x −3y+z =−1
x −y+2z =−3
3x +y−z =9
{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func
tion of Numpy}

In [ ]:
import numpy as np

# Given matrices
A = np.array([[3, 4],
              [7, 8]])

B = np.array([[5, 3],
              [2, 1]])

print("A:\n", A)
print("\nB:\n", B)

# ------------------------------------------------------------
# 1) Prove A * A^-1 = I
A_inv = np.linalg.inv(A)
I = np.eye(2)

print("\n1) A^-1:\n", A_inv)
print("\nA * A^-1:\n", A @ A_inv)
print("\nIs A * A^-1 close to I? ->", np.allclose(A @ A_inv, I))

# ------------------------------------------------------------
# 2) Prove AB != BA
AB = A @ B
BA = B @ A

print("\n2) AB:\n", AB)
print("\nBA:\n", BA)
print("\nIs AB equal to BA? ->", np.array_equal(AB, BA))

# ------------------------------------------------------------
# 3) Prove (AB)^T = B^T * A^T
left_side = (AB).T
right_side = B.T @ A.T

print("\n3) (AB)^T:\n", left_side)
print("\nB^T * A^T:\n", right_side)
print("\nAre they equal? ->", np.array_equal(left_side, right_side))

# ------------------------------------------------------------
# Solve the system of linear equations using inverse method
# 2x − 3y + z  = −1
# x  −  y + 2z = −3
# 3x +  y − z  =  9

# Matrix form: M * X = C
M = np.array([[2, -3,  1],
              [1, -1,  2],
              [3,  1, -1]])

C = np.array([-1, -3, 9])

print("\nCoefficient matrix M:\n", M)
print("\nConstant vector C:\n", C)

# Using inverse: X = inv(M) * C
M_inv = np.linalg.inv(M)
X = M_inv @ C

print("\nSolution [x, y, z]:\n", X)

# Optional check: M @ X should equal C
print("\nCheck (M @ X):\n", M @ X)
print("Is M @ X close to C? ->", np.allclose(M @ X, C))

A:
 [[3 4]
 [7 8]]

B:
 [[5 3]
 [2 1]]

1) A^-1:
 [[-2.    1.  ]
 [ 1.75 -0.75]]

A * A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

Is A * A^-1 close to I? -> True

2) AB:
 [[23 13]
 [51 29]]

BA:
 [[36 44]
 [13 16]]

Is AB equal to BA? -> False

3) (AB)^T:
 [[23 51]
 [13 29]]

B^T * A^T:
 [[23 51]
 [13 29]]

Are they equal? -> True

Coefficient matrix M:
 [[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]

Constant vector C:
 [-1 -3  9]

Solution [x, y, z]:
 [ 2.  1. -2.]

Check (M @ X):
 [-1. -3.  9.]
Is M @ X close to C? -> True
